# Generated by Django 3.2.9 on 2021-11-13 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_usermessage_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usermessage',
            table='usermessage',
        ),
    ]
