# Generated by Django 3.2.9 on 2021-11-16 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_usermessage_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usermessage',
            table='Usermessage',
        ),
    ]
