# Generated by Django 3.2.9 on 2021-11-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brick', '0004_auto_20211109_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='brick',
            name='size',
            field=models.CharField(default='', max_length=20, verbose_name='尺寸'),
        ),
    ]
