# Generated by Django 3.2.9 on 2021-11-13 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brick', '0006_brick_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brick',
            options={'verbose_name': '砖类', 'verbose_name_plural': '砖类'},
        ),
        migrations.AlterField(
            model_name='brick',
            name='quantity',
            field=models.IntegerField(verbose_name='余量'),
        ),
    ]
