# Generated by Django 3.2.9 on 2021-11-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='砖名')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='价钱')),
            ],
        ),
    ]
