# Generated by Django 3.2.9 on 2021-11-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stone',
            name='quantity',
            field=models.IntegerField(default='2000', max_length=50, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='stone',
            name='name',
            field=models.CharField(default='青砖', max_length=50, verbose_name='砖名'),
        ),
    ]
