# Generated by Django 3.2.9 on 2021-11-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stone', '0002_auto_20211109_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stone',
            name='quantity',
            field=models.IntegerField(default='2000', verbose_name='数量'),
        ),
    ]
