# Generated by Django 3.2.9 on 2021-11-13 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stone', '0005_stone_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stone',
            options={'verbose_name': '石头类', 'verbose_name_plural': '石头类'},
        ),
        migrations.AlterField(
            model_name='stone',
            name='quantity',
            field=models.IntegerField(verbose_name='余量'),
        ),
    ]
