# Generated by Django 3.2.9 on 2021-11-16 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_alter_usermessage_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopname', models.CharField(default='', max_length=50, verbose_name='物品名称')),
                ('shopsize', models.CharField(default='', max_length=20, verbose_name='物品大小')),
                ('shopprice', models.DecimalField(decimal_places=2, default='', max_digits=7, verbose_name='物品价钱')),
                ('shopquantity', models.IntegerField(verbose_name='物品余量')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usermessage')),
            ],
            options={
                'verbose_name': '购物车',
                'verbose_name_plural': '购物车',
                'db_table': 'Cart',
            },
        ),
    ]
