# Generated by Django 3.2.9 on 2021-11-16 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='users',
            new_name='usermessage',
        ),
    ]
