# Generated by Django 3.2.9 on 2021-11-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0002_rename_users_cart_usermessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='shopprice',
            field=models.DecimalField(decimal_places=2, default='', max_digits=7, null=True, verbose_name='物品价钱'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='shopquantity',
            field=models.IntegerField(null=True, verbose_name='物品余量'),
        ),
    ]
